package com.example.cab_app_backend.Model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "cars")  // MongoDB Collection
@Data
public class Car {
    @Id
    private String id;   // Auto-generated by MongoDB
    private String model;
    private String licensePlate;
    private int seats;
    private int capacity;   // Engine Capacity in CC
    private int status;  // Available, In Use, Maintenance
    private double pricePerKm;
}
